# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: capi-provider-nico
description: Cluster API infrastructure provider for NICo
type: application
version: 0.1.0
appVersion: "v0.0.0"
keywords:
  - cluster-api
  - capi
  - nico
sources:
  - https://github.com/NVIDIA/cluster-api-provider-nico
