#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate THIRD_PARTY_NOTICES.md: an index and the full license text of every
# Go module linked into the released commands.
#
# Usage:  make notices
#
# Configuration is by environment variable so the same script serves every
# repository in the fleet:
#
#   PACKAGES   space-separated package patterns to analyse   (default "./cmd/...")
#   PLATFORMS  space-separated GOOS/GOARCH pairs             (default "linux/amd64 linux/arm64")
#   OUTPUT     file to write                                 (default THIRD_PARTY_NOTICES.md)
#   GO_LICENSES  path to the pinned binary                   (default ./bin/go-licenses)

set -euo pipefail

# Byte-order collation, so the file is identical on every machine. Without this
# `sort` follows the ambient locale: macOS collates case-insensitively and puts
# github.com/beorn7 before github.com/NVIDIA, while Linux CI uses byte order and
# puts uppercase first. The generated file is then valid on the machine that
# wrote it and "stale" everywhere else, which makes the CI check unusable.
export LC_ALL=C

OUTPUT="${OUTPUT:-THIRD_PARTY_NOTICES.md}"
GO_LICENSES="${GO_LICENSES:-./bin/go-licenses}"
read -r -a PACKAGES <<<"${PACKAGES:-./cmd/...}"

# Accept commas as well as spaces. Several of these Makefiles already use
# PLATFORMS for `docker buildx --platform`, which is comma-separated, and make
# exports a command-line variable into every recipe. Without this, a single
# `make notices PLATFORMS=linux/amd64,linux/arm64` would parse as one platform
# with GOARCH "amd64,linux/arm64".
PLATFORMS_IN="${PLATFORMS:-linux/amd64 linux/arm64}"
read -r -a PLATFORMS <<<"${PLATFORMS_IN//,/ }"

die() { echo "ERROR: $*" >&2; exit 1; }
log() { echo "  $*" >&2; }

# A fenced block must use a fence longer than any backtick run inside it, or a
# license containing a code sample would terminate the block early.
fence_for() {
    local longest
    longest=$(grep -aoE '`+' "$1" 2>/dev/null | awk '{ if (length($0) > n) n = length($0) } END { print n+0 }')
    printf '%*s' $(( longest < 3 ? 3 : longest + 1 )) '' | tr ' ' '`'
}

[[ -x "${GO_LICENSES}" ]] || die "${GO_LICENSES} not found. Run 'make bin/go-licenses'."
command -v go >/dev/null || die "go is not on PATH."

LOCAL_MODULE="$(go list -m)"
[[ -n "${LOCAL_MODULE}" ]] || die "could not determine the local module path."

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT
SAVE_ROOT="${WORK}/save"
LICENSES_DIR="${WORK}/licenses"
CSV="${WORK}/licenses.csv"
mkdir -p "${SAVE_ROOT}" "${LICENSES_DIR}"
: >"${CSV}"

# Collect per platform and merge. A dependency can be reachable on one GOARCH
# and not another, so a single-platform graph under-reports.
#
# Only the local module goes to --ignore. go-licenses already omits the standard
# library, and --ignore matches on plain string prefixes rather than path
# segments, so a short generic prefix silently drops unrelated dependencies —
# "go" would remove golang.org/x/*, google.golang.org/* and gopkg.in/* at once.
# Keep this to the local module.
for platform in "${PLATFORMS[@]}"; do
    goos="${platform%/*}"; goarch="${platform#*/}"
    log "collecting ${goos}/${goarch}"
    save_dir="${SAVE_ROOT}/${goos}_${goarch}"

    GOOS="${goos}" GOARCH="${goarch}" "${GO_LICENSES}" save "${PACKAGES[@]}" \
        --save_path="${save_dir}" --force --ignore="${LOCAL_MODULE}" 2>/dev/null

    GOOS="${goos}" GOARCH="${goarch}" "${GO_LICENSES}" csv "${PACKAGES[@]}" \
        --ignore="${LOCAL_MODULE}" 2>/dev/null >>"${CSV}"

    if [[ -d "${save_dir}" ]]; then
        (cd "${save_dir}" && find . -type f -print0) | while IFS= read -r -d '' f; do
            mkdir -p "${LICENSES_DIR}/$(dirname "${f}")"
            cp -n "${save_dir}/${f}" "${LICENSES_DIR}/${f}" 2>/dev/null || true
        done
    fi
done

[[ -s "${CSV}" ]] || die "go-licenses produced no rows for ${PACKAGES[*]}."

# package -> module@version, so a reader can pin what was actually linked.
MODMAP="${WORK}/modmap"
for platform in "${PLATFORMS[@]}"; do
    goos="${platform%/*}"; goarch="${platform#*/}"
    GOOS="${goos}" GOARCH="${goarch}" go list -deps -buildvcs=false \
        -f '{{if .Module}}{{.ImportPath}} {{.Module.Path}}@{{.Module.Version}}{{end}}' \
        "${PACKAGES[@]}" 2>/dev/null
done | sort -u >"${MODMAP}"

# Join every licence seen for a package rather than taking the first: a package
# may be dual-licensed, and dropping one would misstate the terms.
INDEX="${WORK}/index"
sort -u "${CSV}" | awk -F, 'NF>=3 {
    pkg=$1; url=$2; lic=$3
    if (!(pkg in seen)) { order[++n]=pkg }
    if (index(seen[pkg], lic) == 0) { seen[pkg] = (seen[pkg]=="" ? lic : seen[pkg]" / "lic) }
    link[pkg]=url
} END { for (i=1;i<=n;i++) { p=order[i]; print p "\t" seen[p] "\t" link[p] } }' >"${INDEX}"

TMP="${WORK}/out.md"
{
    cat <<EOF
<!--
  Generated by hack/generate-notices.sh. Do not edit by hand.
  Regenerate with 'make notices'; 'make notices-check' verifies it in CI.
-->

# Third-Party Notices

This project links the Go modules listed below. Their licenses are reproduced in
full so that binaries and container images built from this repository ship with
the attribution those licenses require.

## Scope

Generated from the import closure of \`${PACKAGES[*]}\` in module
\`${LOCAL_MODULE}\`, for $(printf '%s ' "${PLATFORMS[@]}" | sed 's/ $//').

The Go standard library is excluded, as are packages belonging to this module.
Test-only and build-time dependencies that are not reachable from the released
commands are not listed, because they are not distributed.

## Dependency Index

| Package | License | Module |
|---|---|---|
EOF
    while IFS=$'\t' read -r pkg lic url; do
        mod=$(awk -v p="${pkg}" '$1==p {print $2; exit}' "${MODMAP}")
        printf '| [%s](%s) | %s | %s |\n' "${pkg}" "${url}" "${lic}" "${mod:-—}"
    done <"${INDEX}"

    echo
    echo "## License Texts"
    echo

    # Every attribution file for the package, not just the first. go-licenses
    # saves LICENSE and NOTICE side by side, and this loop used to take
    # `sort | head -1` — which under LC_ALL=C always kept LICENSE and always
    # discarded NOTICE. Apache-2.0 section 4(d) requires the NOTICE text to
    # travel with the distribution, and this file is how it travels.
    #
    # The licence file itself comes from the URL go-licenses reported, not from
    # a name pattern. Guessing is how the first attempt at this fix went wrong:
    # go-licenses accepts UNLICENSE and README as licence files (its
    # licenseRegexp is `^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$`), and
    # a narrower allowlist drops such a dependency's entire licence text without
    # a word. The URL's last segment is the file it actually classified;
    # googlesource spells that "<tag>:LICENSE", hence the second strip.
    PKGFILES="${WORK}/pkgfiles"
    while IFS=$'\t' read -r pkg lic url; do
        : >"${PKGFILES}"
        classified="${url##*/}"; classified="${classified##*:}"
        if [[ -n "${classified}" && -f "${LICENSES_DIR}/${pkg}/${classified}" ]]; then
            printf '%s\n' "${LICENSES_DIR}/${pkg}/${classified}" >>"${PKGFILES}"
        fi

        # Plus any NOTICE. go-licenses saves it but never reports it, so it has
        # to be found by name. This is the file the old code discarded.
        find "${LICENSES_DIR}/${pkg}" -maxdepth 1 -type f -iname 'NOTICE*' \
            2>/dev/null >>"${PKGFILES}"

        # Fallback for a reported URL that names no saved file. Mirrors
        # go-licenses' own regexp rather than a narrower guess.
        if [[ ! -s "${PKGFILES}" ]]; then
            find "${LICENSES_DIR}/${pkg}" -maxdepth 1 -type f \
                \( -iname 'LICEN[SC]E*' -o -iname 'UNLICEN[SC]E*' \
                   -o -iname 'COPYING*' -o -iname 'README*' \) \
                2>/dev/null >>"${PKGFILES}"
        fi

        sort -u -o "${PKGFILES}" "${PKGFILES}"
        count=$(wc -l <"${PKGFILES}" | tr -d ' ')
        # Silence here would mean shipping a dependency with no attribution at
        # all, which is the one outcome this file exists to prevent.
        [[ "${count}" -gt 0 ]] || die "no attribution file for ${pkg} (go-licenses reported '${classified}')"

        printf '### %s\n\n' "${pkg}"
        printf '_%s_\n\n' "${lic}"
        while IFS= read -r f; do
            [[ -n "${f}" ]] || continue
            # Name the file only when there is more than one, so the common
            # single-licence case reads exactly as it did before.
            if [[ "${count}" -gt 1 ]]; then printf '**%s**\n\n' "$(basename "${f}")"; fi
            fence=$(fence_for "${f}")
            printf '%s\n' "${fence}"
            cat "${f}"
            printf '\n%s\n\n' "${fence}"
        done <"${PKGFILES}"
    done <"${INDEX}"
} >"${TMP}"

mv "${TMP}" "${OUTPUT}"
log "wrote ${OUTPUT} ($(wc -l <"${OUTPUT}" | tr -d ' ') lines, $(wc -l <"${INDEX}" | tr -d ' ') packages)"
