#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate THIRD_PARTY_NOTICES.md: an index and the full license text of every
# Go module linked into the released commands.
#
# Usage:  make notices
#
# Configuration is by environment variable so the same script serves every
# repository in the fleet:
#
#   PACKAGES   space-separated package patterns to analyse   (default "./cmd/...")
#   PLATFORMS  space-separated GOOS/GOARCH pairs             (default "linux/amd64 linux/arm64")
#   OUTPUT     file to write                                 (default THIRD_PARTY_NOTICES.md)
#   GO_LICENSES  path to the pinned binary                   (default ./bin/go-licenses)

set -euo pipefail

OUTPUT="${OUTPUT:-THIRD_PARTY_NOTICES.md}"
GO_LICENSES="${GO_LICENSES:-./bin/go-licenses}"
read -r -a PACKAGES <<<"${PACKAGES:-./cmd/...}"
read -r -a PLATFORMS <<<"${PLATFORMS:-linux/amd64 linux/arm64}"

die() { echo "ERROR: $*" >&2; exit 1; }
log() { echo "  $*" >&2; }

# A fenced block must use a fence longer than any backtick run inside it, or a
# license containing a code sample would terminate the block early.
fence_for() {
    local longest
    longest=$(grep -oE '`+' "$1" 2>/dev/null | awk '{ if (length($0) > n) n = length($0) } END { print n+0 }')
    printf '%*s' $(( longest < 3 ? 3 : longest + 1 )) '' | tr ' ' '`'
}

[[ -x "${GO_LICENSES}" ]] || die "${GO_LICENSES} not found. Run 'make bin/go-licenses'."
command -v go >/dev/null || die "go is not on PATH."

LOCAL_MODULE="$(go list -m)"
[[ -n "${LOCAL_MODULE}" ]] || die "could not determine the local module path."

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT
SAVE_ROOT="${WORK}/save"
LICENSES_DIR="${WORK}/licenses"
CSV="${WORK}/licenses.csv"
mkdir -p "${SAVE_ROOT}" "${LICENSES_DIR}"
: >"${CSV}"

# Collect per platform and merge. A dependency can be reachable on one GOARCH
# and not another, so a single-platform graph under-reports.
#
# Only the local module goes to --ignore. go-licenses already omits the standard
# library, and --ignore matches on plain string prefixes rather than path
# segments, so a short generic prefix silently drops unrelated dependencies —
# "go" would remove golang.org/x/*, google.golang.org/* and gopkg.in/* at once.
# Keep this to the local module.
for platform in "${PLATFORMS[@]}"; do
    goos="${platform%/*}"; goarch="${platform#*/}"
    log "collecting ${goos}/${goarch}"
    save_dir="${SAVE_ROOT}/${goos}_${goarch}"

    GOOS="${goos}" GOARCH="${goarch}" "${GO_LICENSES}" save "${PACKAGES[@]}" \
        --save_path="${save_dir}" --force --ignore="${LOCAL_MODULE}" 2>/dev/null

    GOOS="${goos}" GOARCH="${goarch}" "${GO_LICENSES}" csv "${PACKAGES[@]}" \
        --ignore="${LOCAL_MODULE}" 2>/dev/null >>"${CSV}"

    if [[ -d "${save_dir}" ]]; then
        (cd "${save_dir}" && find . -type f -print0) | while IFS= read -r -d '' f; do
            mkdir -p "${LICENSES_DIR}/$(dirname "${f}")"
            cp -n "${save_dir}/${f}" "${LICENSES_DIR}/${f}" 2>/dev/null || true
        done
    fi
done

[[ -s "${CSV}" ]] || die "go-licenses produced no rows for ${PACKAGES[*]}."

# package -> module@version, so a reader can pin what was actually linked.
MODMAP="${WORK}/modmap"
for platform in "${PLATFORMS[@]}"; do
    goos="${platform%/*}"; goarch="${platform#*/}"
    GOOS="${goos}" GOARCH="${goarch}" go list -deps -buildvcs=false \
        -f '{{if .Module}}{{.ImportPath}} {{.Module.Path}}@{{.Module.Version}}{{end}}' \
        "${PACKAGES[@]}" 2>/dev/null
done | sort -u >"${MODMAP}"

# Join every licence seen for a package rather than taking the first: a package
# may be dual-licensed, and dropping one would misstate the terms.
INDEX="${WORK}/index"
sort -u "${CSV}" | awk -F, 'NF>=3 {
    pkg=$1; url=$2; lic=$3
    if (!(pkg in seen)) { order[++n]=pkg }
    if (index(seen[pkg], lic) == 0) { seen[pkg] = (seen[pkg]=="" ? lic : seen[pkg]" / "lic) }
    link[pkg]=url
} END { for (i=1;i<=n;i++) { p=order[i]; print p "\t" seen[p] "\t" link[p] } }' >"${INDEX}"

TMP="${WORK}/out.md"
{
    cat <<EOF
<!--
  Generated by hack/generate-notices.sh. Do not edit by hand.
  Regenerate with 'make notices'; 'make notices-check' verifies it in CI.
-->

# Third-Party Notices

This project links the Go modules listed below. Their licenses are reproduced in
full so that binaries and container images built from this repository ship with
the attribution those licenses require.

## Scope

Generated from the import closure of \`${PACKAGES[*]}\` in module
\`${LOCAL_MODULE}\`, for $(printf '%s ' "${PLATFORMS[@]}" | sed 's/ $//').

The Go standard library is excluded, as are packages belonging to this module.
Test-only and build-time dependencies that are not reachable from the released
commands are not listed, because they are not distributed.

## Dependency Index

| Package | License | Module |
|---|---|---|
EOF
    while IFS=$'\t' read -r pkg lic url; do
        mod=$(awk -v p="${pkg}" '$1==p {print $2; exit}' "${MODMAP}")
        printf '| [%s](%s) | %s | %s |\n' "${pkg}" "${url}" "${lic}" "${mod:-—}"
    done <"${INDEX}"

    echo
    echo "## License Texts"
    echo

    while IFS=$'\t' read -r pkg lic url; do
        f=$(find "${LICENSES_DIR}/${pkg}" -maxdepth 1 -type f 2>/dev/null | sort | head -1)
        [[ -n "${f}" ]] || continue
        fence=$(fence_for "${f}")
        printf '### %s\n\n' "${pkg}"
        printf '_%s_\n\n' "${lic}"
        printf '%s\n' "${fence}"
        cat "${f}"
        printf '\n%s\n\n' "${fence}"
    done <"${INDEX}"
} >"${TMP}"

mv "${TMP}" "${OUTPUT}"
log "wrote ${OUTPUT} ($(wc -l <"${OUTPUT}" | tr -d ' ') lines, $(wc -l <"${INDEX}" | tr -d ' ') packages)"
