apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: NicoMachine
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-nico
    app.kubernetes.io/managed-by: kustomize
  name: nicomachine-sample
spec:
  vpcID: vpc-sample
  instanceTypeID: instance-type-sample
  interfaces:
  - subnetID: subnet-sample
