apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: NicoCluster
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-nico
    app.kubernetes.io/managed-by: kustomize
  name: nicocluster-sample
spec:
  siteID: site-sample
