apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.namespaced }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
{{- if .Values.rbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  name: {{ include "cluster-api-provider-nico.resourceName" (dict "suffix" "manager-rolebinding" "context" $) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.rbac.namespaced }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "cluster-api-provider-nico.resourceName" (dict "suffix" "manager-role" "context" $) }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-api-provider-nico.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
